[features]
seeds = false
skip-lint = false

[programs.localnet]
secure_counter = "SECURECOUNTER1111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
