[package]
name = "secure_counter"
version = "0.1.0"
edition = "2021"

[lib]
name = "secure_counter"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
sha2 = "0.10"
hex-literal = "0.4"
