name: Build Anchor Program

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Ubuntu deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config libssl-dev libudev-dev \
            curl ca-certificates gnupg clang llvm make

      - name: Install Solana CLI (GitHub script)
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
          anchor --version

      - name: Build Program
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          anchor build
