name: Build Anchor Program

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Ubuntu deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config libssl-dev libudev-dev \
            curl ca-certificates gnupg clang llvm make

      - name: Install Solana CLI (via cargo)
        run: |
          cargo install solana-cli --locked
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          solana --version

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          anchor --version

      - name: Build Program
        run: |
          anchor build
